'use client';

import React from 'react';
import Link from 'next/link';
import { MarketingNavbar } from '@/components/marketing/MarketingNavbar';
import { MarketingFooter } from '@/components/marketing/MarketingFooter';
import {
  FileText,
  AlertCircle,
  CheckCircle2,
  RefreshCw,
  Building2,
  Lock,
  ArrowRight,
} from 'lucide-react';

export function TermsPageView() {
  return (
    <div className="min-h-screen bg-[#FDFDFC] text-slate-900 font-sans selection:bg-zuva-solar selection:text-white">
      <MarketingNavbar />

      {/* Header Banner */}
      <section className="pt-32 pb-14 border-b border-slate-200/80 bg-gradient-to-b from-orange-50/40 via-white to-[#FDFDFC] relative overflow-hidden">
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-3/4 h-48 bg-gradient-to-b from-zuva-solar/10 to-transparent blur-[110px] pointer-events-none" />

        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center space-y-4 relative z-10">
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-slate-100 border border-slate-200 text-slate-800 text-xs font-bold">
            <FileText className="w-3.5 h-3.5 text-zuva-solar" />
            <span>User Agreement &amp; Operating Policies</span>
          </div>

          <h1 className="text-3xl sm:text-4xl md:text-5xl font-extrabold tracking-tight text-slate-950">
            Terms &amp; Conditions of Service
          </h1>

          <p className="text-sm sm:text-base text-slate-600 max-w-2xl mx-auto leading-relaxed">
            Please read these terms carefully before accessing or using the ZuvaPay platform. By creating an account or transacting on ZuvaPay, you agree to be bound by this agreement.
          </p>

          <p className="text-xs text-slate-400 font-medium">
            Effective Date: September 14, 2026
          </p>
        </div>
      </section>

      {/* Main Terms Body */}
      <section className="py-14 max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="bg-white rounded-3xl border border-slate-200/80 p-6 sm:p-10 shadow-xs space-y-10">

          {/* Critical Third-Party Disclaimer Callout */}
          <div className="p-5 rounded-2xl bg-amber-50/80 border border-amber-200 text-amber-950 text-xs leading-relaxed space-y-2">
            <p className="font-bold flex items-center gap-2 text-sm text-amber-900">
              <AlertCircle className="w-4 h-4 text-amber-600 flex-shrink-0" />
              Crucial Notice on Third-Party Aggregation &amp; Technology Role
            </p>
            <p>
              <strong>ZuvaPay is a technology aggregation platform, not a bank, telecom carrier, or utility generation company.</strong> Many services available on our platform — including but not limited to telecommunications airtime, mobile SME data packages, electricity meter token generation, cable TV renewals, and international virtual phone numbers — are directly provisioned, switched, or generated by independent third-party partners and licensed utilities.
            </p>
          </div>
          {/* Section 1 */}
          <div className="space-y-3">
            <div className="flex items-center gap-2.5 text-slate-900">
              <div className="w-7 h-7 rounded-lg bg-orange-100 text-zuva-solar flex items-center justify-center font-bold text-xs">
                1
              </div>
              <h2 className="text-lg font-bold text-slate-950">Account Eligibility &amp; Security</h2>
            </div>
            <div className="text-xs sm:text-sm text-slate-600 leading-relaxed pl-9 space-y-2">
              <p>
                To register and operate a ZuvaPay wallet, you must be at least 18 years of age and possess legal capacity in the Federal Republic of Nigeria or your operating jurisdiction.
              </p>
              <ul className="list-disc pl-5 space-y-1 text-slate-600">
                <li>You are solely responsible for maintaining the secrecy of your login password and 4-digit transaction PIN.</li>
                <li>Any transaction verified and authorized using your correct transaction PIN is considered executed with your explicit consent and cannot be reversed after carrier dispatch.</li>
                <li>If you suspect unauthorized activity, you must notify our customer desk immediately at <span className="font-medium text-slate-900">hello@zuvapay.com</span>.</li>
              </ul>
            </div>
          </div>

          {/* Section 2 */}
          <div className="space-y-3">
            <div className="flex items-center gap-2.5 text-slate-900">
              <div className="w-7 h-7 rounded-lg bg-orange-100 text-zuva-solar flex items-center justify-center font-bold text-xs">
                2
              </div>
              <h2 className="text-lg font-bold text-slate-950">Third-Party Service Execution &amp; Availability</h2>
            </div>
            <div className="text-xs sm:text-sm text-slate-600 leading-relaxed pl-9 space-y-2">
              <p>
                Because services depend on third-party infrastructure:
              </p>
              <ul className="list-disc pl-5 space-y-1.5 text-slate-600">
                <li><strong>Network Uptime &amp; Delays:</strong> Delivery times for SME data bundles and electricity tokens typically range from 1 to 5 seconds. However, intermittent upstream carrier maintenance, Disco server downtime, or telecommunication congestion can occasionally introduce unavoidable delays.</li>
                <li><strong>Correct Destination Entry:</strong> You are strictly responsible for inputting the correct phone number, meter number, or smartcard number. Once a token is generated or data is dispatched to the entered destination by the upstream vendor, it cannot be recalled or edited.</li>
                <li><strong>Foreign Virtual Lines:</strong> International SMS lines are temporary, dedicated routing channels provided via global telecom aggregators for incoming verification codes. They must not be used for illegal impersonation, fraudulent spamming, or violating third-party platform terms.</li>
              </ul>
            </div>
          </div>

          {/* Section 3 */}
          <div className="space-y-3">
            <div className="flex items-center gap-2.5 text-slate-900">
              <div className="w-7 h-7 rounded-lg bg-orange-100 text-zuva-solar flex items-center justify-center font-bold text-xs">
                3
              </div>
              <h2 className="text-lg font-bold text-slate-950">Debit-First, Instant Automated Refund Policy</h2>
            </div>
            <div className="text-xs sm:text-sm text-slate-600 leading-relaxed pl-9 space-y-2">
              <p>
                We enforce a transparent financial model:
              </p>
              <div className="p-4 rounded-xl bg-slate-50 border border-slate-200 text-slate-700 space-y-1.5">
                <p className="font-semibold text-slate-900 flex items-center gap-1.5">
                  <RefreshCw className="w-3.5 h-3.5 text-emerald-600" />
                  Our Automated Refund Guarantee
                </p>
                <p>
                  If an upstream provider fails to fulfill your order (e.g. carrier gateway timeout or prepaid meter switch unavailable), your debited funds are <strong>automatically returned to your ZuvaPay wallet in full within seconds</strong>. You never need to submit a support ticket to get your money back for a confirmed failed transaction.
                </p>
              </div>
              <p className="text-slate-500 text-xs">
                Wallet balances cannot be subject to arbitrary withholding unless an account is flagged by regulatory authorities for fraudulent, AML-violating, or malicious activity.
              </p>
            </div>
          </div>

          {/* Section 4 */}
          <div className="space-y-3">
            <div className="flex items-center gap-2.5 text-slate-900">
              <div className="w-7 h-7 rounded-lg bg-orange-100 text-zuva-solar flex items-center justify-center font-bold text-xs">
                4
              </div>
              <h2 className="text-lg font-bold text-slate-950">Prohibited Conduct</h2>
            </div>
            <div className="text-xs sm:text-sm text-slate-600 leading-relaxed pl-9 space-y-1.5">
              <p>Users must not engage in:</p>
              <ul className="list-disc pl-5 space-y-1 text-slate-600">
                <li>Automated bot attacks, API scraping, or reverse engineering of ZuvaPay endpoints without a written merchant API agreement.</li>
                <li>Conducting fraudulent transfers, chargebacks, or utilizing stolen payment cards.</li>
                <li>Using virtual communication channels for phishing, illegal scam syndicates, or identity fraud.</li>
              </ul>
            </div>
          </div>

          {/* Section 5 */}
          <div className="space-y-3">
            <div className="flex items-center gap-2.5 text-slate-900">
              <div className="w-7 h-7 rounded-lg bg-orange-100 text-zuva-solar flex items-center justify-center font-bold text-xs">
                5
              </div>
              <h2 className="text-lg font-bold text-slate-950">Limitation of Liability</h2>
            </div>
            <p className="text-xs sm:text-sm text-slate-600 leading-relaxed pl-9">
              To the fullest extent permissible by applicable Nigerian laws, ZuvaPay and its directors shall not be liable for any indirect, punitive, or consequential damages resulting from upstream carrier network blackouts, force majeure events, or user data entry errors. Our total cumulative liability for any verified fulfillment defect is strictly limited to the value of the affected transaction.
            </p>
          </div>

          {/* Section 6 */}
          <div className="space-y-3">
            <div className="flex items-center gap-2.5 text-slate-900">
              <div className="w-7 h-7 rounded-lg bg-orange-100 text-zuva-solar flex items-center justify-center font-bold text-xs">
                6
              </div>
              <h2 className="text-lg font-bold text-slate-950">Governing Law &amp; Dispute Resolution</h2>
            </div>
            <p className="text-xs sm:text-sm text-slate-600 leading-relaxed pl-9">
              These terms are governed by and construed in accordance with the laws of the Federal Republic of Nigeria. In the event of any grievance or dispute, parties agree to first seek amicable settlement via our direct merchant desk before proceeding to mediation in Lagos State.
            </p>
          </div>

          {/* Bottom Back Button */}
          <div className="pt-6 border-t border-slate-100 flex flex-col sm:flex-row items-center justify-between gap-4">
            <Link
              href="/privacy"
              className="text-xs font-semibold text-slate-600 hover:text-zuva-solar flex items-center gap-1.5"
            >
              Review Privacy &amp; NDPC Policy <ArrowRight className="w-3.5 h-3.5" />
            </Link>
            <Link
              href="/"
              className="px-5 py-2.5 rounded-xl bg-slate-900 hover:bg-slate-800 text-white font-bold text-xs transition-colors"
            >
              Back to Home
            </Link>
          </div>
        </div>
      </section>

      <MarketingFooter />
    </div>
  );
}
